@props(['name', 'class' => ''])

@php
$id = $attributes->get('id', '');

$faMap = [
    'user-shield' => 'fas fa-user-shield',
    'cog' => 'fas fa-cog',
    'box' => 'fas fa-box',
    'box-open' => 'fas fa-box-open',
    'tags' => 'fas fa-tags',
    'calendar' => 'far fa-calendar-alt',
    'chalkboard' => 'fas fa-chalkboard',
    'user-tie' => 'fas fa-user-tie',
    'users' => 'fas fa-users',
    'user-friends' => 'fas fa-user-friends',
    'address-book' => 'fas fa-address-book',
    'cart' => 'fas fa-shopping-cart',
    'clipboard-list' => 'fas fa-clipboard-list',
    'clipboard-check' => 'fas fa-clipboard-check',
    'truck' => 'fas fa-truck',
    'handshake' => 'fas fa-handshake',
    'cubes' => 'fas fa-cubes',
    'envelope' => 'fas fa-envelope',
    'tools' => 'fas fa-tools',
    'sign-out' => 'fas fa-sign-out-alt',
    'chevron-down' => 'fas fa-chevron-down',
    'user' => 'fas fa-user',
    'id-card' => 'fas fa-id-card',
    'eye' => 'fas fa-eye',
    'check' => 'fas fa-check',
    'trash' => 'fas fa-trash',
    'plus' => 'fas fa-plus',
    'pencil' => 'fas fa-pencil-alt',
    'arrow-left' => 'fas fa-arrow-left',
    'arrow-right' => 'fas fa-arrow-right',
    'info' => 'fas fa-info-circle',
    'exclamation' => 'fas fa-exclamation-triangle',
    'times' => 'fas fa-times',
    'arrow-up' => 'fas fa-arrow-up',
    'dashboard' => 'fas fa-tachometer-alt',
    'whatsapp' => 'fab fa-whatsapp',
    'facebook' => 'fab fa-facebook',
    'instagram' => 'fab fa-instagram',
    'map-marker' => 'fas fa-map-marker-alt',
    'phone' => 'fas fa-phone',
    'check-circle' => 'fas fa-check-circle',
    'star' => 'fas fa-star',
    'search' => 'fas fa-search',
    'filter' => 'fas fa-filter',
    'grid' => 'fas fa-th',
    'book' => 'fas fa-book',
    'book-open' => 'fas fa-book-open',
    'user-circle' => 'fas fa-user-circle',
    'hourglass' => 'fas fa-hourglass',
    'hammer' => 'fas fa-hammer',
    'paper-plane' => 'fas fa-paper-plane',
    'receipt' => 'fas fa-receipt',
    'boxes' => 'fas fa-boxes',
    'calendar-check' => 'far fa-calendar-check',
    'camera' => 'fas fa-camera',
    'warning' => 'fas fa-exclamation-triangle',
    'sign-in' => 'fas fa-sign-in-alt',
    'times-circle' => 'fas fa-times-circle',
    'tag' => 'fas fa-tag',
    'plus-circle' => 'fas fa-plus-circle',
    'chevron-left' => 'fas fa-chevron-left',
    'chevron-right' => 'fas fa-chevron-right',
    'hand-holding-heart' => 'fas fa-hand-holding-heart',
    'directions' => 'fas fa-directions',
    'user-cog' => 'fas fa-user-cog',
    'menu' => 'fas fa-bars',
    'x' => 'fas fa-times',
    'alert-triangle' => 'fas fa-exclamation-triangle',
    'history' => 'fas fa-history',
    'folder' => 'fas fa-folder',
    'folder-open' => 'fas fa-folder-open',
];

$faClass = $faMap[$name] ?? 'fas fa-circle';
preg_match('/\bw-(\d+)\b/', $class, $m);
$fontSize = $m ? ((int)$m[1] * 4) . 'px' : 'inherit';
@endphp

<i class="{{ $faClass }} {{ $class }}" style="font-size:{{ $fontSize }}"@if($id) id="{{ $id }}"@endif></i>
